# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

#[[main]]
  #name = "Posts"
  #pageRef = "posts"
  #weight = 20

#[[main]]
  #name = "Projects"
  #pageRef = "projects"
  #weight = 30

#[[main]]
#  name = "Forty Forwards"
#  pageRef = "fortyforwards"
#  weight = 40

[[main]]
  name = "Resume"
  pageRef = "resume"
  weight = 50

# [[main]]
#   identifier = "linkedin"
#   pre = "linkedin"
#   url = "https://www.linkedin.com/in/bramhooimeijer"
#   weight = 60
#
# [[main]]
#   identifier = "x-twitter"
#   pre = "x-twitter"
#   url = "https://twitter.com/bramhooimeijer"
#   weight = 64
#
# [[main]]
#   identifier = "github"
#   pre = "github"
#   url = "https://github.com/bramhooimeijer"
#   weight = 68


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20

[[footer]]
  identifier = "f-mail"
  pre = "email"
  url = "mailto:bram@fortyforwards.com"
  weight = 60

[[footer]]
  identifier = "f-linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/bramhooimeijer"
  weight = 61

[[footer]]
  identifier = "f-x-twitter"
  pre = "x-twitter"
  url = "https://twitter.com/bramhooimeijer"
  weight = 64

[[footer]]
  identifier = "f-github"
  pre = "github"
  url = "https://github.com/bramhooimeijer"
  weight = 68
